### ISSUE TITLE
🦺 Project Setup

### ISSUE THREAD

**Issue by dhedgecock** [crystal-ball/componentry-dot-design#18]
## Setup initial project workflows

- [x] Setup dev workflows
- [x] Setup CI workflows
- [x] Setup CD workflows

**Comment by dhedgecock** [comment]
🚀
